name: Recurring BTC Spot Buy

on:
  schedule:
    - cron: '0 0 * * *'  # every day at 8am SGT
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requests
      run: pip install requests

    - name: Run Python script
      env:
        OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
        OKX_SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}
        OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
      run: python buy_usdt_then_btc.py
