name: Recurring BTC Spot Buy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: [self-hosted, okx-static-ip]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      # This will install 'requests' for the system's default Python 3 (3.11 on your VM).
      run: pip install requests

    - name: Run Python script
      env:
        OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
        OKX_SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}
        OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
      # We now just use the default python3 command.
      run: python3 buy.py