name: Recurring BTC Spot Buy

on:
  schedule:
    # This cron expression runs at 00:00 UTC, which is 8am Singapore time (+8).
    # The comment is correct, but be aware that all cron times are UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: [self-hosted, okx-static-ip]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      # It's best practice to list your dependencies in a requirements.txt file.
      # If 'requests' is your only dependency, this is fine, but for more
      # it's better to use 'pip install -r requirements.txt'.
      run: pip install requests

    - name: Run Python script
      env:
        OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
        OKX_SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}
        OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
      run: python buy.py
